config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :pages, only: :index
  resources :producers, only: :index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :producer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy
  has_one_attached :photo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
require "json"
require "open-uri"

class PagesController < ApplicationController
  def home
  end

  def index
    address = params[:search][:address]
    Geocoder.configure(:timeout => 5)
    address_to_geo = Geocoder.search(address)
    coordinates = address_to_geo.first.coordinates #ARRAY
    @coordinates_hash = {
      lat: coordinates[0],
      lng: coordinates[1]
    }
  end
end

app/controllers/producers_controller.rb
require "json"
require "open-uri"

class ProducersController < ApplicationController
  def index
    latitude = params[:lat]
    longitude = params[:lng]

    @search_url = "https://opendata.agencebio.org/api/gouv/operateurs/?lat=#{latitude}&lng=#{longitude}&nb=100&filtrerVenteDetail=1"
    producers_json = URI(@search_url).read
    producers_data = JSON.parse(producers_json)['items']

    producers_data.each do |producer|
      producer['productions'].select! do |production|
        production_category = CategoryMapper.new.call(production['code'])
        production['category'] = production_category
        production_category
      end
      
      producer['nav_link'] = "https://www.google.com/maps/dir/?api=1&destination=#{producer["adressesOperateurs"][0]["lat"]},#{producer["adressesOperateurs"][0]["long"]}&travelmode=driving"
      producer['popup_html'] = render_to_string(partial: "popup", locals: { producer: producer })
    end
    render json: producers_data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BioMap - Trouve les producteurs locaux & bio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>

    <script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-supported/v2.0.0/mapbox-gl-supported.js'></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.9.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.9.2/mapbox-gl.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href= "https://fonts.googleapis.com/css2?family=Lobster+Two&family=McLaren&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poiret+One&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <title><%= meta_title %></title>

    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-container">
  <div class="banner">
    <div class="logo-and-slogan">
      <div class="logo text-center">
        <%= image_tag('logo.svg')%>
      </div>
    </div>
    <div class="searchbar">
      <form action="/pages" method="get">
        <input type="text" name="search[address]" placeholder="Recherche une adresse" required :address>
        <i class="fa fa-search"><input type="submit" class="submit"></i>
      </form>
    </div>
  </div>
  <div class="moto">
    <h2>Trouve les producteurs <span data-controller="typed-js"></span></h2>
  </div>

  <div class="content">
    <div class="card">
      <div class="icon"><i class="fa fa-leaf"></i></div>
      <p class="title">Produits Bio</p>
      <p class="text">Cultures Bio certifiées par le Ministère de l'Agriculture.</p>
    </div>

    <div class="card">
      <div class="icon" id="card2"><i class="fa fa-tractor"></i></div>
        <p class="title">Producteurs locaux</p>
        <p class="text">Consomme locale, où que tu sois.</p>
    </div>

    <div class="card">
      <div class="icon"><i class="fas fa-map-marker-alt"></i></div>
        <p class="title">Itinéraire</p>
        <p class="text">Rends toi chez les producteurs aux alentours.</p>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="index"
  data-controller="filter nav mapbox"
  data-mapbox-location-value="<%= @coordinates_hash.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
  data-action="filter->mapbox#filter coordinatesChanged->nav#coordinatesChanged">

  <%= render "shared/side_search_col" %>

  <div class="map" data-mapbox-target="mapElement">
    <div class="loading" data-mapbox-target='loading'>
      <div>
        <p>récupération des carottes</p>
        <p><span data-controller="loading-typed"></span></p>
      </div>
    </div>
    <div class="localize-me-container d-flex justify-content-center align-items-center">
      <i class="fas fa-crosshairs localize-me" data-action="click->mapbox#localizeMe"></i>
    </div>
  </div>

</div>

app/views/producers/_popup.html.erb
<div>
  <div class="popup-banner"
      data-nav-target='card'>
      <% if producer['denominationcourante'].present? %>
        <h3><%= producer['denominationcourante'] %></h3>
      <% else %>
        <h3><%= producer['raisonSociale'] %></h3>
      <% end %>
  </div>
  <div class="producer-infos">
    <div class="address">
      <% if producer["adressesOperateurs"][0]["lieu"].present? %>
        <p>
          <i class="fas fa-map-marker-alt"></i>
          <%= producer["adressesOperateurs"][0]["lieu"]%>,
          <%= producer["adressesOperateurs"][0]["codePostal"] %>
          <%= producer["adressesOperateurs"][0]["ville"] %>
        </p>
        <i class="fas fa-plus-circle address-add" data-action="click->nav#add" data-producer="<%= producer.to_json %>"></i>
      <% end %>
    </div>
    <% if producer['telephone'].present? %>
      <p><i class="fas fa-phone"></i> <%= producer['telephone'] %>
        <% if producer['telephoneCommerciale'].present? %>
          / <%= producer['telephoneCommerciale'] %>
        <% end %>
      </p>
    <% end %>
    <% if producer['email'].present? %>
      <p>
        <i class="fas fa-envelope"> </i>
        <%= producer['email'] %>
      </p>
    <% end %>
    <% if producer['sitesWeb'].present? %>
      <p>
        <i class="fas fa-globe"> </i>
        <%= producer['sitesWeb']['url'] %>
        (<%= producer['sitesWeb']['typeSiteWeb'] %>)
      </p>
    <% end %>
  </div>

  <div class="product-infos">
    <div class="category">
      <p><strong>Categories:</strong></p>
      <ul style="list-style: none">
        <% categories = producer['productions'].map {|production| production['category']}.uniq %>
        <% categories.each do |category|%>
          <li>
            <%= CategoryMapper::MAPPING[category]['name'] %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="productions">
      <p><strong>Productions:</strong></p>
      <ul style="list-style: none">
        <% producer["productions"].take(5).each do |production| %>
          <li>
            <%= production["nom"] %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="popup-footer">
    <a class="navigation" href="<%= producer["nav_link"] %>" target="_blank">J'y vais</a>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search_bar.html.erb
<%= simple_form_for :search, class:"searchbar", url: pages_path , method: :get do |f| %>
  <%= f.input :address %>
  <%= f.submit "search", class:"fa fa-search" %>
<% end %>

app/views/shared/_side_search_col.html.erb
<div class="filter-column">
  <%= link_to root_path do %>
    <%= image_tag('logo.svg')%>
   <% end %>
  <h3>Catégories</h3>
    <div class="select-all" data-filter-target="selectButton" data-action="click->filter#selectAllCategories">Tout sélectionner</div>
  <div class="cat-items" >
    <% CategoryMapper::MAPPING.each do |category_id, category|  %>
      <%= check_box_tag category_id, category_id, false, class:"check", data: { "action" => "click->filter#update", 'filter-target' => 'category' } %><label for=<%= category_id %>><%= category['name'] %></label>
    <% end %>
  </div>
  <div class="itinary-card">
    <div class="itinary-title">
      <i class="fas fa-minus-circle" data-nav-target="clear" data-action='click->nav#clearList'></i>
      <h3>Itinéraire</h3>
      <a class="btn-nav" href="#" data-nav-target="navlink" target="_blank"><i class="fas fa-location-arrow"></i></a>
    </div>
    <p>Click sur <strong>+</strong> pour ajouter un producteur dans la liste de navigation</p>

    <ol data-nav-target='navlist'>
    </ol>
  </div>
</div>